package com.adoc.rrhh.entity.enums;

public enum TipoAusencia {
    INCAPACIDAD_ENFERMEDAD,
    INCAPACIDAD_ACCIDENTE,
    INCAPACIDAD_MATERNIDAD,
    AUSENCIA_JUSTIFICADA_CON_GOCE,
    AUSENCIA_JUSTIFICADA_SIN_GOCE,
    AUSENCIA_INJUSTIFICADA
}
